#!/usr/bin/env bash
# One-shot production provisioning for Extreme Print Management System
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

ENV_FILE="${EPMS_ENV_FILE:-deploy/production.generated.env}"
DATA_DIR="${EPMS_DATA_DIR:-$ROOT/data}"

mkdir -p "$DATA_DIR" sdk/jars/incoming

if [[ ! -f "$ENV_FILE" ]]; then
  SESSION_SECRET="$(python3 -c 'import secrets; print(secrets.token_urlsafe(48))')"
  AGENT_TOKEN="$(python3 -c 'import secrets; print(secrets.token_urlsafe(48))')"
  ADMIN_PASS="$(python3 -c 'import secrets; print(secrets.token_urlsafe(16))')"
  cat >"$ENV_FILE" <<EOF
# Generated by provision_production.sh — store securely
EPMS_PRODUCTION=1
EPMS_HOST=0.0.0.0
EPMS_PORT=8080
EPMS_DB=$DATA_DIR/extreme-print-management.sqlite3
EPMS_SESSION_SECRET=$SESSION_SECRET
EPMS_AGENT_TOKEN=$AGENT_TOKEN
EPMS_REQUIRE_AUTH=true
EPMS_ANONYMIZE_DOCS=true
EPMS_AUDIT_RETENTION_DAYS=365
EPMS_BOOTSTRAP_ADMIN_PASSWORD=$ADMIN_PASS
EPMS_SEED_DEMO=0
EOF
  echo "Created $ENV_FILE"
  echo "Bootstrap admin password: $ADMIN_PASS"
fi

set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

python3 scripts/download_vendor_sdks.py --all || true
python3 -m unittest discover -s tests -q

echo ""
echo "Provision complete."
echo "Start server:  set -a && source $ENV_FILE && set +a && python3 app_production.py"
echo "Health:        curl http://127.0.0.1:8080/api/health"
echo "Checklist:     curl http://127.0.0.1:8080/api/production/checklist"
echo "Device SDK:    curl http://127.0.0.1:8080/extreme/sdk/v1/health"
